### ISSUE TITLE
Implement memory footprint mode

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#123]
Implement a new mode and possibly a new operator for computing the memory footprint that has overloads for no serializable but sizable elements like `std::function<>` or pointers (just count the point size and then follow it).

**Comment by lifflander** [comment]
@PhilMiller

**Comment by cz4rs** [comment]
reopening to add support for more types

**Comment by PhilMiller** [comment]
Rather then re-opening, let's just open a new issue. That makes tracking of what request has or hasn't been fulfilled somewhat easier.

**Comment by cz4rs** [comment]
closing and moving the change into a new issue
