### ISSUE TITLE
Test vt in CI

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/checkpoint#125]
Changes in checkpoint can break vt. Currently, vt CI and normal development runs against whatever happens to be on checkpoint's `develop` branch. Given that, we should do full continuous *integration*, and test checkpoint changes against vt, as well as its internal tests.

**Comment by cz4rs** [comment]
one way to do it would be to just trigger some builds in `vt` by sending a `repository_dispatch` event from `checkpoint` as described here:
https://github.community/t/triggering-by-other-repository/16163

if we decide to trigger it only after a merge to checkpoint's `develop`, we don't even need to play around with the branch name in `build_cpp.sh`

**Comment by cz4rs** [comment]
one downside: since it's just running a `curl` on checkpoint side, the vt build result will not be visible (some workaround possible?)

**Comment by cz4rs** [comment]
for reference:
https://github.com/peter-evans/repository-dispatch
(marketplace link: https://github.com/marketplace/actions/repository-dispatch)

**Comment by jstrzebonski** [comment]
Whole adding compilation results to vt PRs' comments is done with dispatching without any 3rd party and it's not rocket science to do, but as @cz4rs stated that way build results won't be easily visible in checkpoint PR (another dispatch had to be done from vt to checkpoint with build result :- ] ).

But it shouldn't be that hard to add another pipeline that simply does full build (vt + PR's checkpoint).
