### ISSUE TITLE
Add support for more types in memory footprinting mode

### ISSUE THREAD

**Issue by cz4rs** [DARMA-tasking/checkpoint#127]
adding memory footprinting for vt components (DARMA-tasking/vt#1009) requires more types to be supported:

- [x] `std::stack`
- [x] `void*`
- [x] `std::map` with `std::unique_ptr` mapped type 
- [x] `std::_List_iterator<T>`
- [x] ~~non-intrusive serializer for `omp_lock_t` (and any other OpenMP types used)~~
note: just count the size without diving into implementation
- [x] ~~handle pure abstract interface (case of `vt::vrt::collection::balance::LoadModel`)~~
note: this should be handled on the `vt` side using virtual serialization
- [x] ~~handle ambiguous case, when a type both `hasNoninSerialize`, `isEnum` (`enum class vt::vrt::collection::balance::LBType`)~~
note: this should be handled on `vt` side, remove custom `serialize` for enum class

note: this is a followup on #123

**Comment by PhilMiller** [comment]
For `LoadModel`, we should use checkpoint virtual serialization, which means the necessary change should be purely in vt
