### ISSUE TITLE
Unpacking of containers default-constructs elements rather than using reconstruction logic

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/checkpoint#161]
For `std::vector<T> v`, the current code calls `s | len; v.resize(len)`, which results in calling the default constructor `T::T()`. This may not be valid code at all, for some types. For other types, the default constructor could be needlessly expensive. This violates the usual stated contract serialization offers, that reconstruction should use a tagged constructor if one is defined.

**Comment by PhilMiller** [comment]
I believe that the scrupulously correct strategy for types that should be treated with this care is to reserve sufficient capacity (see #162) , and then reconstruct elements one at a time, using calls to `v.emplace_back(args)`. The ultimate implementation may act something like

```
for (size_t i = 0; i < size; ++i) {
  v.emplace_back(RECONSTRUCT_TAG);
  s | v.back();
}
```

However, that `emplace_back` call seems to be out of place. I think we actually want to centralize that logic in the reconstruction code, rather than duplicating/diffusing it to containers as well. Thus, I'll offer a straw-man proposal along the following lines (taking advantage of [N3649](http://wg21.link/n3649), defined in C++14):

```
std::vector<SpecialType> v;
auto emplacer = [&v] (auto && ... args) { v.emplace_back(std::forward<decltype(args...)>(args...)); };
for (size_t i = 0; i < size; ++i) {
  dispatch::call_with_reconstruct_arguments_for<SpecialType>(emplacer);
  s | v.back();
}
```

Where that latter function is defined to come up with arguments of the same type as reconstruction does now, and pass them to the lambda it receives, rather than to an object constructor.

**Comment by lifflander** [comment]
We already have classes (`Reconstructor`) that centralize this logic. We might need to extend it a little for this, but we do have an API that knows all the ways to reconstruct and tries them in a particular order.

**Comment by PhilMiller** [comment]
My point was more that the container serializers uniformly don't call `Reconstructor` for the elements

**Comment by cz4rs** [comment]
suggested test case: use vector of a class with default constructor deleted
