### ISSUE TITLE
Warnings in examples with Intel 18

### ISSUE THREAD

**Issue by PhilMiller** [DARMA-tasking/checkpoint#172]
```
/ascldap/users/pbmille/repos/EMPIRE/TPL/checkpoint/examples/checkpoint_example_3.cc(58): warning #3868: declaration hides member "checkpoint::examples::TestReconstruct::a" (declared at line 52) in same scope
      auto a = new (buf) TestReconstruct(100);
           ^

/ascldap/users/pbmille/repos/EMPIRE/TPL/checkpoint/examples/checkpoint_example_2.cc(59): warning #3868: declaration hides member "checkpoint::examples::MyTest::a" (declared at line 52) in same scope
      MyTest* a = new (buf) MyTest(100);
              ^
```

**Comment by lifflander** [comment]
@PhilMiller Is this issue still relevant? If so, let's assign it to someone..

**Comment by jstrzebonski** [comment]
@lifflander @PhilMiller 
I don't see any warnings on Intel 18 pipeline.

**Comment by cz4rs** [comment]
Closing - could not reproduce.
`icc-18` build is clean at the moment, also `-Werror` has been enabled for all workflows.

**Comment by cz4rs** [comment]
Some additional insight for Intel compiler's warnings:
https://stackoverflow.com/a/36166507

@PhilMiller If you are still experiencing this, please post complete compilation command - maybe we don't have some of the warnings enabled.

**Comment by PhilMiller** [comment]
I haven't looked at this in a long time, so I'll trust that the clean builds mean we're good.
