### ISSUE TITLE
Add typeid name/type registry to pack/unpack to confirm class correctness

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#174]
@jstrzebonski Overall, the goal is to improve error checking in checkpoint. This issue is to register class IDs with the type register when we serialize to check if the same class is being traversed in the same order when de-serializing. Right now, we only register types for polymorphic classes because we need to reconstruct them based on runtime type information. In an error checking mode, we want to extend this registration to all classes and then put this information into the serialized buffer so we can check if the traversal matches the same types during de-serialization.

**Comment by PhilMiller** [comment]
Should we abstract a type registry class out so that we can instantiate it for the various use cases we have?
