### ISSUE TITLE
std::unordered_map serializer causing huge memory explosion with empty container

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#180]
This code seems like it has a bug that is causing a huge number of unordered_map nodes to be allocated even though the target container is actually empty the entire time. It's causing a massive growth of hundreds of megabytes:

```C++
template <typename SerializerT, typename ContainerT>
inline void serializeUnorderedAssociativeContainer(
  SerializerT& s, ContainerT& cont
) {
  if (not s.isFootprinting()) {
    auto max_load_factor = cont.max_load_factor();
    s | max_load_factor;
    cont.max_load_factor(max_load_factor);

    auto bucket_count = cont.bucket_count();
    s | bucket_count;
    cont.rehash(bucket_count);
  }

  serializeMapLikeContainer(s, cont);
}
```

At the very least we should not be rehashing everything during sizing and packing! That has linear complexity.

<img width="1610" alt="Screen Shot 2021-03-03 at 2 25 31 PM" src="https://user-images.githubusercontent.com/3324465/109881020-78ade680-7c2c-11eb-8998-c12e27337c70.png">
<img width="1683" alt="Screen Shot 2021-03-03 at 2 25 46 PM" src="https://user-images.githubusercontent.com/3324465/109881003-73e93280-7c2c-11eb-91d9-b6702d3ecc43.png">

**Comment by PhilMiller** [comment]
Does it work to stick a `if (s.isUnpacking())` before the `rehash` call?

**Comment by lifflander** [comment]
We can probably start by writing a unit test (@cz4rs) to try to reproduce this problem locally. I think we pushed the latest checkpoint code out to EMPIRE so we need to fix that ASAP.

**Comment by lifflander** [comment]
> Does it work to stick a `if (s.isUnpacking())` before the `rehash` call?

I haven't tried that... I'm just removing the code altogether to ensure all the memory increase is due to this.

**Comment by cz4rs** [comment]
looking into it right now, I'll try `isUnpacking` after setting up the test

**Comment by lifflander** [comment]
With those lines completely commented out the memory usage looks like this:

<img width="1849" alt="Screen Shot 2021-03-03 at 2 34 25 PM" src="https://user-images.githubusercontent.com/3324465/109881721-9b8cca80-7c2d-11eb-8daf-28466f82c4a8.png">

**Comment by cz4rs** [comment]
@lifflander @PhilMiller I have creted a PR trying to call `rehash` only when necessary (`s.isUnpacking()` only cuts the calls number roughly in half).
