### ISSUE TITLE
Improve non-intrusive serialization documentation and examples

### ISSUE THREAD

**Issue by nlslatt** [DARMA-tasking/checkpoint#249]
Current examples are intrusive. Add non-intrusive examples. Be sure to make it clear that the non-intrusive serializer must go in ~~the checkpoint (or later magistrate) namespace~~ the same namespace as the type being serialized.

**Comment by PhilMiller** [comment]
We might want to implement and document use of some subsidiary namespace, like `magistrate:: intrusive`, rather than the top level namespace, to avoid collisions. The first case I can think of would be for a type that we later implement our own serializer for

**Comment by PhilMiller** [comment]
For purposes of this documentation, stick the new serializer definitions in a namespace matching that of the type being serialized
