### ISSUE TITLE
Compilation with GCC-13 produces many notes about snprintf

### ISSUE THREAD

**Issue by thearusable** [DARMA-tasking/checkpoint#311]
When compiling magistrate with GCC-13 there will be many notes about `snprintf` which makes the compilation output not readable.

Example note:
/Users/arus/NGA/DARMA/vt/lib/checkpoint/src/checkpoint/dispatch/reconstructor.h:157:13: note: 'snprintf' output 196 bytes into a destination of size 8
157 |     snprintf(
       |     ~~~~~~~~^
  158 |       &msg[0], sizeof(msg),
      |       ~~~~~~~~~~~~~~~~~~~~~
  159 |       "Checkpoint is failing to reconstruct a class %s, due to it being "
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |       "abstract or the absence of a suitable constructor (default or tagged) "
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |       "or reconstruct()",
      |       ~~~~~~~~~~~~~~~~~~~
  162 |       typeid(T).name()
      |       ~~~~~~~~~~~~~~~~
  163 |     );
      |     ~

**Comment by nlslatt** [comment]
This is also a problem for MacOS

**Comment by nlslatt** [comment]
@thearusable Can you please get to this issue soon?

**Comment by thearusable** [comment]
@nlslatt Sure, I'll start to work on this shortly.
