### ISSUE TITLE
rename `checkpoint_virtual_serialize` macros to `magistrate_virtual_serialize`

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#376]
Note that `checkpoint_virtual_serialize` macros were never renamed to `magistrate_virtual_serialize`.

_Originally posted by @cz4rs in https://github.com/DARMA-tasking/magistrate/pull/375#discussion_r1838789367_

**Comment by cz4rs** [comment]
TODO:
- add `magistrate_virtual_serialize...` macros
- mark the `checkpoint` ones as deprecated
