### ISSUE TITLE
Code coverage for Kokkos header files

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#7]
Extract code coverage info for kokkos serialization code to better understand how comprehensive the serialization code is.

**Comment by cz4rs** [comment]
Coverage report is generated in `gcc-7` build and uploaded to codecov.io (https://app.codecov.io/gh/DARMA-tasking/checkpoint).

Codecov report is configured to appear in PRs as well:
![image](https://user-images.githubusercontent.com/4639165/117318162-75ccad80-ae8a-11eb-8b3a-37caf15f10bf.png)
