### ISSUE TITLE
Write serializer for KokkosCrsMatrix

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#75]

**Comment by lifflander** [comment]
Merged, closing

**Comment by uhetmaniuk** [comment]
@lifflander @PhilMiller 
Is there a test for serializing a Kokkos::CrsMatrix variable?

In EMPIRE I serialized / deserialized one Kokkos::CrsMatrix variable, everything looks correct except the number of columns.
In the output of deserialization, the number of columns was incorrectly set to 0.

Please advise whether I should reproduce this issue outside of EMPIRE-PIC
