### ISSUE TITLE
Write serializer for Kokkos::DynRankView

### ISSUE THREAD

**Issue by lifflander** [DARMA-tasking/checkpoint#79]

**Comment by lifflander** [comment]
Is this needed anymore? I don't think so. Leaving it open until I know for sure

**Comment by PhilMiller** [comment]
EMPIRE-PIC diagnostics have the relevant logic open-coded. We can just copy it in. The basic approach is to look at the rank, and then bounce through a flattened `View`

**Comment by PhilMiller** [comment]
It's relatively little code in EMPIRE-PIC right now, and the complicated bits are actually in the consumption of the deserialized view anyway, not in the serialization itself. This can be deferred

**Comment by lifflander** [comment]
Per this issue, we should make progress on this issue: https://cee-gitlab.sandia.gov/EM-Plasma/EMPIRE/-/merge_requests/1127#note_487371
